{{- include "helm-chart.validateConfig" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
data:
  CRONBIRD_LISTEN: {{ .Values.config.listen | quote }}
  CRONBIRD_IDENTITIES: {{ .Values.config.identities | quote }}
  CRONBIRD_ALLOW_DYNAMIC: {{ .Values.config.allowDynamic | quote }}
  CRONBIRD_PERSIST_PATH: {{ .Values.config.persistPath | quote }}
  CRONBIRD_PERSIST_INTERVAL: {{ .Values.config.persistInterval | quote }}
  CRONBIRD_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
