{{- if .Values.config.secrets.authToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  {{- with .Values.config.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  CRONBIRD_AUTH_TOKEN: {{ .Values.config.secrets.authToken | quote }}
{{- end }}
